services:
  db:
    image: postgres:15-alpine
    container_name: lab4_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super_password
      POSTGRES_DB: spring_lab3_notifications
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab4_spring_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/spring_lab3_notifications
      - DB_USERNAME=postgres
      - DB_PASSWORD=super_password

volumes:
  pgdata: